parameters:

    session_memcached_host:          127.0.0.1 
    redis_host:                     172.20.0.6
    
    app.compactSite:            false  
    app.compactVersion:         /min 
    app.cdn:                    '' 
    app.catalogsPath:           '/home/prod/catalogs/'

imports:    
    - { resource: parameters.custom.template_dev.yml }

    