<?php

namespace AppBundle\Repository;

/**
 * BookmakerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookmakerRepository extends \Doctrine\ORM\EntityRepository
{
}
