<?php

namespace AppBundle\Repository;

/**
 * GroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function setCacheUtility( $secondLevelCacheUtility ) {
        $this->secondLevelCacheUtility = $secondLevelCacheUtility;
    }
    
    public function findCommentsByDataArticle( $articleId, $limit ) {
        $limit = explode(',', $limit);
        $firstResult = count($limit) == 1 ? 0 : $limit[0];
        $lastResult = count($limit) == 1 ? $limit[0] : $limit[1];
        
         $query = $this->getEntityManager()->createQuery( 
            'SELECT c FROM AppBundle:Comment c WHERE c.dataArticle ='.$articleId.'order by c.createAt DESC' 
        )
                ->setFirstResult($firstResult)
                ->setMaxResults($lastResult);
        
        $query->setCacheable( SECOND_LEVEL_CACHE_ENABLED );
        $query->setCacheRegion( 'my_comment_region_query' );
                
        if( FIRST_LEVEL_CACHE_ENABLED && ( !SECOND_LEVEL_CACHE_ENABLED || !$query->isCacheable() ) ) {
            $query->useQueryCache( FIRST_LEVEL_CACHE_ENABLED );
            $query->useResultCache(FIRST_LEVEL_CACHE_ENABLED, BANNER_REGION_TTL, 'comment_findCommentsByDataArticle_CacheORM');    
        }        
        $result = $query->getResult();     
        if( SECOND_LEVEL_CACHE_ENABLED ||  SECOND_LEVEL_CACHE_SET_EXPIRE_ENABLED  )
            $this->secondLevelCacheUtility->setExpire( 'comment', POLL_REGION_TTL );
        
        return $result;
    }
    
    
    public function countCommentsByDataArticle( $articleId ) {
         $query = $this->getEntityManager()->createQuery( 
            'SELECT COUNT(c) as tot FROM AppBundle:Comment c WHERE c.dataArticle ='.$articleId.'order by c.createAt DESC' 
        );
        
        $query->setCacheable( SECOND_LEVEL_CACHE_ENABLED );
        $query->setCacheRegion( 'my_comment_region_query' );
                
        if( FIRST_LEVEL_CACHE_ENABLED && ( !SECOND_LEVEL_CACHE_ENABLED || !$query->isCacheable() ) ) {
            $query->useQueryCache( FIRST_LEVEL_CACHE_ENABLED );
            $query->useResultCache(FIRST_LEVEL_CACHE_ENABLED, BANNER_REGION_TTL, 'comment_countCommentsByDataArticle_CacheORM');    
        }
        
        $result = $query->getSingleResult();     
        
        if( SECOND_LEVEL_CACHE_ENABLED ||  SECOND_LEVEL_CACHE_SET_EXPIRE_ENABLED  )
            $this->secondLevelCacheUtility->setExpire( 'comment', POLL_REGION_TTL );
        
        return $result;
    }
}
