<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentArticleRepository extends \Doctrine\ORM\EntityRepository
{   
    
    public function setCacheUtility( $secondLevelCacheUtility ) {
        $this->secondLevelCacheUtility = $secondLevelCacheUtility;
    }
    
      
      // metodo che recupera tutti gli articoli per l'admin
    
    public function getAllArticlesFosElastica() {
       $repository = $this->getEntityManager()->getRepository('AppBundle:DataArticle');

       $qb = $repository->createQueryBuilder('da');
       $qb->select('da,ca');       
       $qb->join('da.contentArticle', 'ca');
       $qb->join('da.priorityImg', 'img');
       $qb->where('da.status = 1 ');
       $qb->orderBy("da.publishAt", 'DESC');
       
       return $qb; 
        

    }
    
    
}
