<?php

namespace AppBundle\Repository;

/**
 * GroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function setCacheUtility( $secondLevelCacheUtility ) {
        $this->secondLevelCacheUtility = $secondLevelCacheUtility;
    }
    
    /*
     * Query che ritorna tutti i gruppi 
     */
    public function findGroups( $toArray = false) {
        $sql = 'SELECT gr FROM AppBundle:Group gr';
        $query = $this->getEntityManager()->createQuery( $sql );
        
        try {
            $query->setCacheable( true );
            $query->setCacheRegion( 'my_group_region_query' );

            if( !SECOND_LEVEL_CACHE_ENABLED || !$query->isCacheable() ) {
                $query->useQueryCache( true );
                $query->useResultCache(true, GROUP_REGION_TTL, 'group_findGroups_CacheORM'.md5( $sql ) );    
            }      
       
            $result = $query->getResult();    
            
            if( SECOND_LEVEL_CACHE_ENABLED ||  SECOND_LEVEL_CACHE_SET_EXPIRE_ENABLED  )
                $this->secondLevelCacheUtility->setExpire( 'group', GROUP_REGION_TTL );
            
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }          
        return $result;
    }
}
