<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HouseRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function setCacheUtility( $secondLevelCacheUtility ) {
        $this->secondLevelCacheUtility = $secondLevelCacheUtility;
    }
    
    
    public function getHouses( $get ) {        
        $where = 'WHERE 1=1 ';
        if( isset( $get['checkStatus'] ) && $get['checkStatus'] != '-1' ) {
            $where .= 'AND h.checkStatus = '.$get['checkStatus'];
        }
        
        if( !empty( $get['locals'] ) ) {
            $where .= 'AND h.locals = '.$get['locals'];
        }
                
        if( !empty( $get['bathroom'] ) ) {
            $where .= 'AND h.bathroom = '.$get['bathroom'];
        }        
                
        if( !empty( $get['floor'] ) ) {
            $where .= 'AND h.floor = '.$get['floor'];
        }        
        
        if( !empty( $get['price'] ) ) {
            $where .= 'AND h.price <= '.$get['price'];
        }        
        
        if( !empty( $get['surface'] ) ) {
            $where .= 'AND h.surface <= '.$get['surface'];
        }        
        
        $sql = 'SELECT h FROM AppBundle:House h '.$where.' ORDER BY h.id desc';        
        $query = $this->getEntityManager()->createQuery( $sql );
        $result =  $query->getResult();
        
        return $result;
    }
    
}


