<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MegazineSectionRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function setCacheUtility( $secondLevelCacheUtility ) {
        $this->secondLevelCacheUtility = $secondLevelCacheUtility;
    }
    
    /**
     * Crea la query con la cache
     * @param type $toArray
     * @return type
     */
    public function findByNameUrl( $name ) {
//        $sql = "SELECT s,m,t FROM AppBundle:Subcategory s 
//                LEFT JOIN s.model m
//                LEFT JOIN m.trademark t
//                WHERE s.nameUrl = '".$name."' ORDER BY t.name asc, m.dateImport desc"; 
        $sql = "SELECT m FROM AppBundle:MegazineSection m WHERE m.nameUrl = '".$name."' "; 
        $query = $this->getEntityManager()->createQuery( $sql )->setMaxResults(1);          
        
        $query->setCacheable( true );
        $query->setCacheRegion( 'my_megazinesection_region_query' );
                
        if( !SECOND_LEVEL_CACHE_ENABLED || !$query->isCacheable() ) {
            $query->useQueryCache( true );
            $query->useResultCache(true, CATEGORY_REGION_TTL, 'megazinesection_findByNameUrl_CacheORM'.md5( $sql ) );    
        } 
        
        $result = $query->getOneOrNullResult();
        if( SECOND_LEVEL_CACHE_ENABLED ||  SECOND_LEVEL_CACHE_SET_EXPIRE_ENABLED  )
            $this->secondLevelCacheUtility->setExpire( 'megazinesection', CATEGORY_REGION_TTL );
        
        return $result;
    }
    
}
