<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatsFeedAffiliationRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function setCacheUtility( $secondLevelCacheUtility ) {
        $this->secondLevelCacheUtility = $secondLevelCacheUtility;
    }
       
    public function findCountAll(  $limit = false ) {                
        $query = $this->getEntityManager()->createQuery( 
            'SELECT count(s) as tot FROM AppBundle:StatsFeedAffiliation s ' 
        );              
        $result = $query->getSingleResult();      
        
        return $result;
    }
    
    /**
     * Crea la query con la cache
     * @param type $toArray
     * @return type
     */
    public function findAll(  $limit = false ) {                
        $query = $this->getEntityManager()->createQuery( 
            'SELECT s FROM AppBundle:StatsFeedAffiliation s order by s.id DESC' 
        );
        
        if( !empty( $limit ) ) {
            $limit = explode(',', $limit);
            $firstResult = count($limit) == 1 ? 0 : $limit[0];
            $lastResult = count($limit) == 1 ? $limit[0] : $limit[1];
            $query->setFirstResult($firstResult)
            ->setMaxResults($lastResult);         
        }
        
        $result = $query->getResult();      
        
        return $result;
    }
}
