<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Image extends \AppBundle\Entity\Image implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Image' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Image' . "\0" . 'src', '' . "\0" . 'AppBundle\\Entity\\Image' . "\0" . 'titleImg', '' . "\0" . 'AppBundle\\Entity\\Image' . "\0" . 'widthSmall', '' . "\0" . 'AppBundle\\Entity\\Image' . "\0" . 'heightSmall', '' . "\0" . 'AppBundle\\Entity\\Image' . "\0" . 'widthMedium', '' . "\0" . 'AppBundle\\Entity\\Image' . "\0" . 'heightMedium', '' . "\0" . 'AppBundle\\Entity\\Image' . "\0" . 'widthBig', '' . "\0" . 'AppBundle\\Entity\\Image' . "\0" . 'heightBig', '' . "\0" . 'AppBundle\\Entity\\Image' . "\0" . 'search', 'dataArticles'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Image' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Image' . "\0" . 'src', '' . "\0" . 'AppBundle\\Entity\\Image' . "\0" . 'titleImg', '' . "\0" . 'AppBundle\\Entity\\Image' . "\0" . 'widthSmall', '' . "\0" . 'AppBundle\\Entity\\Image' . "\0" . 'heightSmall', '' . "\0" . 'AppBundle\\Entity\\Image' . "\0" . 'widthMedium', '' . "\0" . 'AppBundle\\Entity\\Image' . "\0" . 'heightMedium', '' . "\0" . 'AppBundle\\Entity\\Image' . "\0" . 'widthBig', '' . "\0" . 'AppBundle\\Entity\\Image' . "\0" . 'heightBig', '' . "\0" . 'AppBundle\\Entity\\Image' . "\0" . 'search', 'dataArticles'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Image $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function validate(\Symfony\Component\Validator\Context\ExecutionContextInterface $context)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'validate', [$context]);

        return parent::validate($context);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataArticle($dataArticle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataArticle', [$dataArticle]);

        return parent::setDataArticle($dataArticle);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataArticle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataArticle', []);

        return parent::getDataArticle();
    }

    /**
     * {@inheritDoc}
     */
    public function setSrc($src)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSrc', [$src]);

        return parent::setSrc($src);
    }

    /**
     * {@inheritDoc}
     */
    public function getSrc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSrc', []);

        return parent::getSrc();
    }

    /**
     * {@inheritDoc}
     */
    public function setWidthSmall($widthSmall)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWidthSmall', [$widthSmall]);

        return parent::setWidthSmall($widthSmall);
    }

    /**
     * {@inheritDoc}
     */
    public function getWidthSmall()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWidthSmall', []);

        return parent::getWidthSmall();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeightSmall($heightSmall)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeightSmall', [$heightSmall]);

        return parent::setHeightSmall($heightSmall);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeightSmall()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeightSmall', []);

        return parent::getHeightSmall();
    }

    /**
     * {@inheritDoc}
     */
    public function setWidthMedium($widthMedium)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWidthMedium', [$widthMedium]);

        return parent::setWidthMedium($widthMedium);
    }

    /**
     * {@inheritDoc}
     */
    public function getWidthMedium()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWidthMedium', []);

        return parent::getWidthMedium();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeightMedium($heightMedium)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeightMedium', [$heightMedium]);

        return parent::setHeightMedium($heightMedium);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeightMedium()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeightMedium', []);

        return parent::getHeightMedium();
    }

    /**
     * {@inheritDoc}
     */
    public function setWidthBig($widthBig)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWidthBig', [$widthBig]);

        return parent::setWidthBig($widthBig);
    }

    /**
     * {@inheritDoc}
     */
    public function getWidthBig()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWidthBig', []);

        return parent::getWidthBig();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeightBig($heightBig)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeightBig', [$heightBig]);

        return parent::setHeightBig($heightBig);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeightBig()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeightBig', []);

        return parent::getHeightBig();
    }

    /**
     * {@inheritDoc}
     */
    public function addDataArticle(\AppBundle\Entity\DataArticle $dataArticle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDataArticle', [$dataArticle]);

        return parent::addDataArticle($dataArticle);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDataArticle(\AppBundle\Entity\DataArticle $dataArticle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDataArticle', [$dataArticle]);

        return parent::removeDataArticle($dataArticle);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataArticles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataArticles', []);

        return parent::getDataArticles();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleImg($titleImg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleImg', [$titleImg]);

        return parent::setTitleImg($titleImg);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleImg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleImg', []);

        return parent::getTitleImg();
    }

    /**
     * {@inheritDoc}
     */
    public function setSearch($search)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSearch', [$search]);

        return parent::setSearch($search);
    }

    /**
     * {@inheritDoc}
     */
    public function getSearch()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSearch', []);

        return parent::getSearch();
    }

}
